# Generated by Django 5.1.2 on 2024-11-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_delete_category_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routinerecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
