# Generated by Django 5.1.2 on 2024-11-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_book_is_deleted_routinerecord_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='No description available.', max_length=200),
            preserve_default=False,
        ),
    ]
