# Generated by Django 5.1.2 on 2024-11-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_alter_book_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
