# Generated by Django 5.1.2 on 2024-11-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0008_rename_cover_image_book_coverimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutineRecord',
        ),
    ]
