# Generated by Django 5.1.2 on 2024-10-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('time', models.DurationField()),
                ('content', models.TextField(max_length=200)),
            ],
        ),
    ]
