# Generated by Django 5.1.2 on 2024-11-15 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clublist', '0001_initial'),
        ('mylibrary', '0011_book_user'),
        ('routinelist', '0003_alter_routine_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clublist.club'),
        ),
        migrations.AddField(
            model_name='routine',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RoutineComplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.book')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routinelist.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
