# Generated by Django 5.1.2 on 2024-11-15 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routinelist', '0003_alter_routine_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('content', models.TextField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='club_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserJoinedRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clublist.club')),
                ('personalRoutine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routinelist.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
